### ISSUE TITLE
CSS and HTML distribution

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/dialog#327]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-rc.1.0.3

**Please tell us about your environment:**
* **Operating System:**
all

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
all

* **Browser:**
all

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
The styles are inlined in [src/dialog-configuration.ts](https://github.com/aurelia/dialog/blob/433010255ee7e38aa03614a186293c964a93c63c/src/dialog-configuration.ts#L21).
The views are also inlined using the `@inlineView`.

**Expected/desired behavior:**

* **What is the expected behavior?**
We should get them out in a separate file/s. At least the style.

* **What is the motivation / use case for changing the behavior?**
Currently the styles - that one-liner,  are nightmare to maintain. Also the *html* can not be minified.

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect @ZHollingshead can you give some input based on the `ux` repos experience?
The dialog current approach, of inlining the styles, does not require any additional configuring of the loader/bundler. But maintainability/readability/build integration is :scream:

**Comment by ZHollingshead** [comment]
Is there a reason we can not set the individual pieces up as regular custom component modules like so?

ux-dialog.ts
```typescript
import { customElement } from 'aurelia-templating';

@customElement('ux-dialog')
export class UxDialog {

}
```

ux-dialog.html
```html
<template>
  <require from="./ux-dialog.css"></require>
  
  <slot></slot>
</template>
```

ux-dialog.css
```css
ux-dialog {
  display: table;
  box-shadow: 0 5px 15px rgba(0, 0, 0, .5);
  border: 1px solid rgba(0, 0, 0, .2);
  border-radius: 5px;
  padding: 3px;
  min-width: 300px;
  width: -moz-fit-content;
  width: -webkit-fit-content;
  width: fit-content;
  height: -moz-fit-content;
  height: -webkit-fit-content;
  height: fit-content;
  margin: auto;
  border-image-source: initial;
  border-image-slice: initial;
  border-image-width: initial;
  border-image-outset: initial;
  border-image-repeat: initial;
  background: #fff
}
```
