### ISSUE TITLE
No dialog-overlay background color showing

### ISSUE THREAD

**Issue by nano2nd** [aurelia/dialog#39]
Dialog appears but does not overlay the view underneath. I see the overlay element in the DOM called "dialog-overlay" but appears to be missing a background-color.

**Comment by PWKad** [comment]
If you want your dialog overlay to have styling or color you can add it in your CSS.  Just add something like - 

```css
ai-dialog-overlay.active {
  background-color: black;
  opacity: .5;
}
```
