### ISSUE TITLE
Dialog not re-centered when re-sizing browser

### ISSUE THREAD

**Issue by chrismbeckett** [aurelia/dialog#51]
A quick guess is you are using JavaScript to calculate the margins for the dialog container since they are being added as an inline style?

- the position of the dialog is not being re-centered when you resize the browser
- using JavaScript to get the screen dimensions is gonna cause a world of hurt on mobile browsers (often report incorrect screen sizes and screw up on orientation changes)
- using inline styles means you can't override the positioning with custom CSS

There are pure CSS approaches to centering a div element that would work better than a fixed calculated margin.

You might want to consider vertical alignment with transform:

http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/

Its also really easy if you are using flexbox with something like this:

```css
.ai-dialog-container {
  display: flex;
  align-items: center;
  justify-content: center;
}

.ai-dialog {
  display: flex;
  flex-grow: 0;
  height: 300px;
  width: 300px;
}
```

I can work on this if you would prefer a pull-request with a solution. Let me know!
